name: tests

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  # Label of the container job
  clickhouse:
    strategy:
      matrix:
        dbversion: ['clickhouse/clickhouse-server']
        go: ['1.21', '1.22']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    services:
      clickhouse:
        image: ${{ matrix.dbversion }}
        env:
          CLICKHOUSE_DB: gorm
          CLICKHOUSE_USER: gorm
          CLICKHOUSE_PASSWORD: gorm
        ports:
          - 9941:8123
          - 9942:9000
          - 9943:9009

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Tests
      run: go test

